# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f03f460eaf3d3628a6bdc3f600c5a4efe6c62757ee4905d24bc25ffeef8589aa656e567cca08bc86dcbf1066ded6c7deedb7e5c043091919306b936d8427dd9

test:
  secret_key_base: f29048adc04c868153a3af547589f9d1897b330d9d96443c9d0682f063f6b616f0c54561807cb0fbaedd685ea5ad3530640df34b94c15454b6ee00f38e3ea0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
